[toolchain]
# `mise` set the env var RUSTUP_TOOLCHAIN and in docker use the provided toolchain => no channel set
# But some ci/workflow (release*) doesn't use mise
channel = "1.86.0"
components = ["rustc", "cargo", "rust-std", "clippy", "rustfmt", "llvm-tools"]
profile = "minimal"
